# Generated by Django 4.2.1 on 2023-05-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friendshiprequest_friendship_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendshiprequest',
            options={'verbose_name': 'Заявка в друзья', 'verbose_name_plural': 'Заявки в друзья'},
        ),
        migrations.RemoveConstraint(
            model_name='friendshiprequest',
            name='unique request',
        ),
        migrations.AddConstraint(
            model_name='friendshiprequest',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique request'),
        ),
    ]
